settings:
  legacy:
    force: false
    interval: 100ms
server:
  status: true
  open: true
  port: 5001
  host: localhost
schema:
- name: dkg
  path: .
  commands:
    test:
      status: true
  watcher:
    paths:
    - /
    extensions:
    - go
    ignored_paths:
    - .git
    - .realize
    - vendor
